---
- name: Launch EC2 instance
  local_action: ec2 
                group={{ security_group }} 
                instance_type={{ instance_type}} 
                image={{ ami_id }} 
                wait=true 
                region={{ region }} 
                keypair={{ keypair }}
                count={{count}}
                vpc_subnet_id={{ vpc_subnet_id }}
  register: ec2

- name: Add EC2 instance(s) to the local ansible inventory file
  local_action: lineinfile 
                dest="/home/vagrant/hosts" 
                regexp={{ item.public_ip }} 
                insertafter="[EC2]" line={{ item.public_ip }}
  with_items: '{{ ec2.instances }}'

# - name: Wait for SSH to come up
#  local_action: wait_for 
#                host={{ item.public_ip }} 
#                port=22 
#                state=started
#  with_items: ec2.instances

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: '{{ ec2.instances }}'
  args:
    tags:
     Name: ansible
