---

- name: python-pip 
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-pip

- name: awscli
  pip: name=awscli

# - name: Set home directory of the user
#   set_fact:
#    home_dir: /home/{{ aws_cli_user }}

- name: Create the AWS config directory
  file:
    path={{ aws_cli_user_home }}/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0755

- name: Copy AWS CLI config
  template:
    src=aws_cli_config.j2
    dest={{ aws_cli_user_home }}/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644

